-- Publicera hela FAQ:n från doldadress.se/vanliga-fragor i kunskapsbasen.
-- Idempotent: matchar på (tenantId, slug). Säker att köra om.
-- Tenant: doldadress.  searchVector fylls automatiskt (GENERATED).
BEGIN;

-- 1) Publika kategorier
WITH t AS (SELECT id FROM "Tenant" WHERE id = 'doldadress' OR subdomain = 'doldadress' LIMIT 1)
INSERT INTO "KnowledgeCategory" ("id","tenantId","name","slug","sortOrder","isPublic","createdAt","updatedAt")
SELECT gen_random_uuid()::text, t.id, v.name, v.slug, v."sortOrder", true, now(), now()
FROM t CROSS JOIN (VALUES
  ('Jag vill bli kund', 'jag-vill-bli-kund', 0),
  ('Ny kund', 'ny-kund', 1),
  ('Avindexering', 'avindexering', 2),
  ('Registrering', 'registrering', 3),
  ('Upplysningar', 'upplysningar', 4),
  ('Adresslarm', 'adresslarm', 5),
  ('Hackskydd och dark web-bevakning', 'hackskydd-och-dark-web-bevakning', 6),
  ('Prenumeration', 'prenumeration', 7),
  ('Fakturasupport', 'fakturasupport', 8),
  ('Övrigt', 'ovrigt', 9),
  ('Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 10),
  ('Kontoinställningar', 'kontoinstallningar', 11),
  ('Uppsägning och ångerrätt', 'uppsagning-och-angerratt', 12),
  ('Teknisk support', 'teknisk-support', 13),
  ('Vår support', 'var-support', 14),
  ('Övriga frågor', 'ovriga-fragor', 15),
  ('ID-skydd', 'id-skydd', 16),
  ('Betalning', 'betalning', 17)
) AS v(name, slug, "sortOrder")
ON CONFLICT ("tenantId","slug") DO UPDATE
  SET "name" = EXCLUDED."name", "sortOrder" = EXCLUDED."sortOrder", "isPublic" = true, "updatedAt" = now();

-- 2) Artiklar (AI-aktiva + publicerade i hjälpcentret)
WITH t AS (SELECT id FROM "Tenant" WHERE id = 'doldadress' OR subdomain = 'doldadress' LIMIT 1)
INSERT INTO "KnowledgeBase" ("id","tenantId","title","content","excerpt","category","categoryId","tags","slug","isActive","isPublic","status","sortOrder","relatedIds","viewCount","createdAt","updatedAt")
SELECT gen_random_uuid()::text, t.id, v.title, v.content, v.excerpt, v.category,
       (SELECT c.id FROM "KnowledgeCategory" c WHERE c."tenantId" = t.id AND c.slug = v."categorySlug"),
       ARRAY[v.tag]::text[], v.slug, true, true, 'published', v."sortOrder",
       ARRAY[]::text[], 0, now(), now()
FROM t CROSS JOIN (VALUES
  ('jag-ar-intresserad-av-era-tjanster-beratta-lite-mer-om-vad-det-innebar', 'Jag är intresserad av era tjänster. Berätta lite mer om vad det innebär?', 'Vad roligt att du är intresserad! Våra tjänster hjälper dig att skydda din privata information online genom att ta bort känsliga uppgifter som kan utnyttjas av andra. På så sätt minskar vi din synlighet på nätet och gör det svårare för obehöriga att komma åt dina privata uppgifter.

Vi avindexerar länkar på Google som innehåller information du inte vill ska vara synlig, till exempel från upplysningssajter, Flashback-trådar, bilder på Google, nyhetsartiklar eller Lexbase. Det kan handla om länkar som visas när någon söker på ditt namn eller dina personuppgifter. Vi hjälper dig att ta bort dessa länkar från Googles sökresultat. Vi kan avindexera alla länkar om dig, så länge de inte berör allmänintresse.

Utöver detta hjälper vi dig att bli borttagen från upplysningssajters hemsidor: **Mrkoll.se, Ratsit.se, Hitta.se, Birthday.se, Merinfo.se, Eniro.se och Upplysning.se**. Vi övervakar även din synlighet på dessa sajter. Om du blir återpublicerad får du en varning direkt från oss, allt kan du följa på Mina sidor.

Adresslarm ingår också i tjänsten. Vi övervakar din folkbokföringsadress och skickar en varning direkt om någon obehörig skriver sig där.

Därtill erbjuder vi hack-skydd som innebär att vi kontinuerligt övervakar konton kopplade till din registrerade e-postadress. Vi meddelar dig direkt om dina uppgifter dyker upp, så att du kan agera omedelbart.

Fler detaljer om hur våra tjänster fungerar i detalj hittar du här: [Doldadress | Hur det fungerar](https://www.doldadress.se/tjanster).', 'Vad roligt att du är intresserad! Våra tjänster hjälper dig att skydda din privata information online genom att ta bort känsliga uppgifter som kan utnyttjas av…', 'Jag vill bli kund', 'jag-vill-bli-kund', 'Jag vill bli kund', 0),
  ('hur-blir-jag-kund-hos-er', 'Hur blir jag kund hos er?', 'Klicka på knappen "Kom igång" uppe till höger på vår webbplats, välj det paket som passar dig och registrera dig. Därefter är du igång och får tillgång till våra tjänster. Välkommen!', 'Klicka på knappen "Kom igång" uppe till höger på vår webbplats, välj det paket som passar dig och registrera dig.', 'Jag vill bli kund', 'jag-vill-bli-kund', 'Jag vill bli kund', 1),
  ('behover-jag-teckna-en-prenumeration-for-att-bli-kund', 'Behöver jag teckna en prenumeration för att bli kund?', 'Ja, det är en prenumerationstjänst. När du registrerar dig väljer du själv det betalningsalternativ som passar dig bäst.', 'Ja, det är en prenumerationstjänst. När du registrerar dig väljer du själv det betalningsalternativ som passar dig bäst.', 'Jag vill bli kund', 'jag-vill-bli-kund', 'Jag vill bli kund', 2),
  ('hur-kommer-man-igang-med-tjansten-blev-precis-kund', 'Hur kommer man igång med tjänsten, blev precis kund?', 'Välkommen till oss! För att komma igång behöver du först skapa ditt konto på Mina sidor. Klicka på registrerings länken i mailet du fått från oss och följ instruktionerna. När kontot är skapat kan du logga in och börja använda våra tjänster direkt.', 'Välkommen till oss! För att komma igång behöver du först skapa ditt konto på Mina sidor.', 'Ny kund', 'ny-kund', 'Ny kund', 0),
  ('hur-loggar-jag-in', 'Hur loggar jag in?', 'Klicka på knappen "Logga in" uppe till höger på vår webbplats. Logga sedan in med din registrerade e-postadress och ditt lösenord.', 'Klicka på knappen "Logga in" uppe till höger på vår webbplats. Logga sedan in med din registrerade e-postadress och ditt lösenord.', 'Ny kund', 'ny-kund', 'Ny kund', 1),
  ('vad-behover-jag-gora', 'Vad behöver jag göra?', 'När ditt konto är skapat kan du börja dölja dig från upplysningssajternas hemsidor direkt via våra guider på Mina sidor.

Avindexeringen på Google sköter vi åt dig. Du väljer själv vilka länkar du vill att vi ska ta bort. På Mina sidor hittar du en lista med rekommenderade länkar vi redan identifierat, och du kan även skicka in fler länkar på egen hand.

Vi övervakar kontinuerligt nya länkar som dyker upp på Google och skickar en notis till dig så snart vi hittar något nytt. Vi bevakar även din synlighet på upplysningssajternas hemsidor.

Har du ett Premium-abonnemang kan du lägga till två e-postadresser på ditt konto. Vi bevakar dessa för att upptäcka eventuella dataläckor och skydda dig mot att dina uppgifter sprids eller missbrukas.

Adresslarm ingår i alla våra paket. Vi övervakar om någon skriver sig på din adress och skickar en notis direkt om det skulle hända.', 'När ditt konto är skapat kan du börja dölja dig från upplysningssajternas hemsidor direkt via våra guider på Mina sidor.', 'Ny kund', 'ny-kund', 'Ny kund', 2),
  ('vad-innebar-det-att-bli-avindexerad-pa-google', 'Vad innebär det att bli avindexerad på Google?', 'Att bli avindexerad på Google innebär att vi tar bort specifika länkar från sökresultatet, till exempel när man söker på ditt namn. När en länk är avindexerad visas den alltså inte längre bland sökträffarna på Google.', 'Att bli avindexerad på Google innebär att vi tar bort specifika länkar från sökresultatet, till exempel när man söker på ditt namn.', 'Avindexering', 'avindexering', 'Avindexering', 0),
  ('vilka-lankar-kan-ni-ta-bort', 'Vilka länkar kan ni ta bort?', 'Vi kan ta bort länkar som innehåller personliga uppgifter om dig, till exempel namn, adress, telefonnummer, personnummer, lön eller arbetsplats. Det gäller även bilder där du syns eller där dina uppgifter framgår, liksom forumtrådar, nyhetsartiklar och uppgifter från upplysningssajter (t.ex. Mrkoll.se, Hitta.se, Eniro.se), Lexbase, Krimfup samt profilinformation kopplad till biluppgifter.', 'Vi kan ta bort länkar som innehåller personliga uppgifter om dig, till exempel namn, adress, telefonnummer, personnummer, lön eller arbetsplats.', 'Avindexering', 'avindexering', 'Avindexering', 1),
  ('vilka-lankar-kan-ni-inte-ta-bort', 'Vilka länkar kan ni inte ta bort?', 'Vi kan inte ta bort länkar som inte handlar om dig, som berör allmänintresse eller ta bort dina egna konton på sociala medier. Vi kan ta bort viss information som gäller exempelvis bolagsuppgifter, vissa kriminella handlingar eller brott, information om dig som politiker, men inte allt eftersom det kan beröra allmänt intresse.', 'Vi kan inte ta bort länkar som inte handlar om dig, som berör allmänintresse eller ta bort dina egna konton på sociala medier.', 'Avindexering', 'avindexering', 'Avindexering', 2),
  ('kan-jag-valja-vilka-lankar-som-ska-avindexeras', 'Kan jag välja vilka länkar som ska avindexeras?', 'Ja. Du väljer själv vilka länkar du vill få avindexerade. Vi tar fram rekommendationer som du kan skicka in med ett klick, men vi rekommenderar också att du själv googlar ditt namn för att se om det finns fler länkar du vill skicka in.', 'Ja. Du väljer själv vilka länkar du vill få avindexerade. Vi tar fram rekommendationer som du kan skicka in med ett klick, men vi rekommenderar också att du…', 'Avindexering', 'avindexering', 'Avindexering', 3),
  ('hur-lang-tid-tar-det-innan-lankar-blir-avindexerade', 'Hur lång tid tar det innan länkar blir avindexerade?', 'Vår genomsnittliga handläggningstid är cirka 13 dagar. I vissa fall kan det ta upp till 8 veckor, men det är mer ovanligt.', 'Vår genomsnittliga handläggningstid är cirka 13 dagar. I vissa fall kan det ta upp till 8 veckor, men det är mer ovanligt.', 'Avindexering', 'avindexering', 'Avindexering', 4),
  ('var-kan-jag-folja-mina-arenden', 'Var kan jag följa mina ärenden?', 'På Mina sidor under fliken Avindexering kan du följa alla dina ärenden. Där ser du vilka länkar som skickats in, vilka som bearbetas och vilka som har blivit borttagna.', 'På Mina sidor under fliken Avindexering kan du följa alla dina ärenden.', 'Avindexering', 'avindexering', 'Avindexering', 5),
  ('kostar-rekommenderade-lankar-extra-nar-ni-gor-lanksokning-at-mig', 'Kostar rekommenderade länkar extra när ni gör länksökning åt mig?', 'Nej, självklart inte. Våra rekommenderade länkar är en service för att underlätta för dig, så att du med ett knapptryck kan välja vilka länkar du vill att vi ska avindexera.', 'Nej, självklart inte. Våra rekommenderade länkar är en service för att underlätta för dig, så att du med ett knapptryck kan välja vilka länkar du vill att vi…', 'Avindexering', 'avindexering', 'Avindexering', 6),
  ('jag-blev-precis-kund-men-fick-ingen-registreringslank-hur-gor-jag', 'Jag blev precis kund men fick ingen registreringslänk, hur gör jag?', 'Om du saknar din registreringslänk, börja med att kontrollera skräppost. Ibland kan länken dröja någon timme. Se också till att du fått en beställningsbekräftelse och att du angivit rätt e-postadress vid registreringen. Har du råkat skriva fel e-postadress, eller om något annat inte stämmer, kontakta vår support så hjälper vi dig.', 'Om du saknar din registreringslänk, börja med att kontrollera skräppost. Ibland kan länken dröja någon timme.', 'Registrering', 'registrering', 'Registrering', 0),
  ('kan-jag-registrera-mig-hos-er-om-jag-har-sekretessmarkering', 'Kan jag registrera mig hos er om jag har sekretessmarkering?', 'Nej, tyvärr är det inte möjligt.', 'Nej, tyvärr är det inte möjligt.', 'Registrering', 'registrering', 'Registrering', 1),
  ('behover-jag-ha-mobilt-bankid-for-att-kunna-registrera-mig-hos-er', 'Behöver jag ha mobilt BankID för att kunna registrera mig hos er?', 'Ja, du behöver ha tillgång till mobilt BankID för att kunna bli kund hos oss.', 'Ja, du behöver ha tillgång till mobilt BankID för att kunna bli kund hos oss.', 'Registrering', 'registrering', 'Registrering', 2),
  ('kan-jag-registrera-flera-konton-pa-samma-e-postadress', 'Kan jag registrera flera konton på samma e-postadress?', 'Nej, varje konto är knutet till en unik e-postadress.', 'Nej, varje konto är knutet till en unik e-postadress.', 'Registrering', 'registrering', 'Registrering', 3),
  ('jag-har-varit-kund-hos-er-tidigare-kan-jag-registrera-mig-igen', 'Jag har varit kund hos er tidigare, kan jag registrera mig igen?', 'Självklart, det går utmärkt att registrera sig på nytt.', 'Självklart, det går utmärkt att registrera sig på nytt.', 'Registrering', 'registrering', 'Registrering', 4),
  ('vilka-kriterier-har-ni-for-registrering-av-kunder', 'Vilka kriterier har ni för registrering av kunder?', 'För att kunna bli kund hos oss behöver du vara minst 18 år gammal, vara folkbokförd i Sverige samt inte ha skyddade uppgifter. Tjänsten kan alltså erbjudas till myndiga personer som finns i det svenska folkbokföringsregistret, och tyvärr inte till personer med sekretessmarkerad identitet.', 'För att kunna bli kund hos oss behöver du vara minst 18 år gammal, vara folkbokförd i Sverige samt inte ha skyddade uppgifter.', 'Registrering', 'registrering', 'Registrering', 5),
  ('vilka-upplysningssajter-blir-jag-borttagen-fran', 'Vilka upplysningssajter blir jag borttagen från?', 'Vi hjälper dig att bli borttagen från Mrkoll.se, Ratsit.se, Hitta.se, Birthday.se, Merinfo.se, Eniro.se och Upplysning.se. När du blir dold på sajterna innebär det att din profil tas bort från deras hemsidor och att det inte längre går att hitta din profil där.', 'Vi hjälper dig att bli borttagen från Mrkoll.se, Ratsit.se, Hitta.se, Birthday.se, Merinfo.se, Eniro.se och Upplysning.se.', 'Upplysningar', 'upplysningar', 'Upplysningar', 0),
  ('blir-min-profil-helt-borttagen-fran-ratsit-och-mrkoll', 'Blir min profil helt borttagen från Ratsit och Mrkoll?', 'Ja. Hela din profil tas bort från Ratsit och Mrkoll, vilket innebär att varken ditt namn eller dina uppgifter längre finns synliga på deras hemsidor.', 'Ja. Hela din profil tas bort från Ratsit och Mrkoll, vilket innebär att varken ditt namn eller dina uppgifter längre finns synliga på deras hemsidor.', 'Upplysningar', 'upplysningar', 'Upplysningar', 1),
  ('hur-lang-tid-tar-det-att-bli-borttagen-fran-sajterna', 'Hur lång tid tar det att bli borttagen från sajterna?', 'Borttagningen sker oftast direkt eller inom en vecka, men i vissa fall kan det ta upp till två månader.', 'Borttagningen sker oftast direkt eller inom en vecka, men i vissa fall kan det ta upp till två månader.', 'Upplysningar', 'upplysningar', 'Upplysningar', 2),
  ('vad-hander-om-nagon-av-sajterna-aterpublicerar-min-profil', 'Vad händer om någon av sajterna återpublicerar min profil?', 'Det händer ibland att en upplysningssajt, exempelvis Mrkoll.se, återpublicerar en profil. Men ingen fara, vi övervakar din synlighet på sajterna och skickar en varning direkt om du blir återpublicerad, så att du snabbt kan bli dold igen.', 'Det händer ibland att en upplysningssajt, exempelvis Mrkoll.se, återpublicerar en profil.', 'Upplysningar', 'upplysningar', 'Upplysningar', 3),
  ('var-hittar-jag-adresslarmet', 'Var hittar jag Adresslarmet?', 'Du hittar Adresslarm på Mina sidor under fliken Adresslarm.', 'Du hittar Adresslarm på Mina sidor under fliken Adresslarm.', 'Adresslarm', 'adresslarm', 'Adresslarm', 0),
  ('hur-fungerar-adresslarmet', 'Hur fungerar Adresslarmet?', 'Vi bevakar din folkbokföringsadress och meddelar dig om någon registrerar sig där utan din vetskap, en metod som tyvärr ofta utnyttjas av kriminella. Via ditt konto kan du enkelt se vilka som är folkbokförda på din adress. Vid en nyregistrering på din adress får du en omedelbar notis från oss, så att du kan agera i tid.', 'Vi bevakar din folkbokföringsadress och meddelar dig om någon registrerar sig där utan din vetskap, en metod som tyvärr ofta utnyttjas av kriminella.', 'Adresslarm', 'adresslarm', 'Adresslarm', 1),
  ('skyddar-adresslarmet-alla-som-bor-pa-min-adress', 'Skyddar Adresslarmet alla som bor på min adress?', 'Nej. Ditt konto är personligt, och det är endast du som registrerad användare som får notiser från oss om någon skriver sig på din adress.', 'Nej. Ditt konto är personligt, och det är endast du som registrerad användare som får notiser från oss om någon skriver sig på din adress.', 'Adresslarm', 'adresslarm', 'Adresslarm', 2),
  ('vad-gor-jag-om-nagon-obehorig-folkbokfor-sig-pa-min-adress', 'Vad gör jag om någon obehörig folkbokför sig på min adress?', 'Om någon är felaktigt folkbokförd på din adress bör du omgående meddela Skatteverket via deras tjänst "Meddela felaktig folkbokföring".', 'Om någon är felaktigt folkbokförd på din adress bör du omgående meddela Skatteverket via deras tjänst "Meddela felaktig folkbokföring".', 'Adresslarm', 'adresslarm', 'Adresslarm', 3),
  ('vad-innebar-hackskydd', 'Vad innebär hackskydd?', 'Hackskydd (Dark Web-bevakning) innebär att vi kontinuerligt övervakar konton kopplade till din registrerade e-postadress. Vårt system genomsöker över 15 miljarder läckta konton på Dark Web och meddelar dig direkt om dina uppgifter dyker upp, så att du kan agera omedelbart.', 'Hackskydd (Dark Web-bevakning) innebär att vi kontinuerligt övervakar konton kopplade till din registrerade e-postadress.', 'Hackskydd och dark web-bevakning', 'hackskydd-och-dark-web-bevakning', 'Hackskydd och dark web-bevakning', 0),
  ('jag-har-fatt-mejl-om-att-mina-uppgifter-finns-i-en-datalacka-vad-gor-jag', 'Jag har fått mejl om att mina uppgifter finns i en dataläcka, vad gör jag?', 'Om vi hittar dina uppgifter i en läcka får du en notis av oss med information om var läckan skett och vilken typ av data som exponerats. På Mina sidor kan du söka på den e-postadress du bevakar för att se mer detaljer. Det viktigaste du kan göra är att omedelbart byta lösenord på de berörda kontona. För extra skydd rekommenderar vi också att du aktiverar tvåstegsverifiering.', 'Om vi hittar dina uppgifter i en läcka får du en notis av oss med information om var läckan skett och vilken typ av data som exponerats.', 'Hackskydd och dark web-bevakning', 'hackskydd-och-dark-web-bevakning', 'Hackskydd och dark web-bevakning', 1),
  ('kan-jag-kontrollera-om-min-e-postadress-finns-i-en-lacka', 'Kan jag kontrollera om min e-postadress finns i en läcka?', 'Ja. Som Premiumkund kan du bevaka upp till två e-postadresser samtidigt. Vi kontrollerar dem automatiskt och meddelar dig om de påträffas i en läcka.', 'Ja. Som Premiumkund kan du bevaka upp till två e-postadresser samtidigt. Vi kontrollerar dem automatiskt och meddelar dig om de påträffas i en läcka.', 'Hackskydd och dark web-bevakning', 'hackskydd-och-dark-web-bevakning', 'Hackskydd och dark web-bevakning', 2),
  ('hur-vet-jag-vilken-prenumeration-jag-har-valt', 'Hur vet jag vilken prenumeration jag har valt?', 'När du blir kund väljer du det paket du önskar. På ditt kvitto står vilket paket du köpt, och på Mina sidor under fliken prenumeration hittar du ytterligare detaljer om ditt abonnemang.', 'När du blir kund väljer du det paket du önskar. På ditt kvitto står vilket paket du köpt, och på Mina sidor under fliken prenumeration hittar du ytterligare…', 'Prenumeration', 'prenumeration', 'Prenumeration', 0),
  ('fornyas-min-prenumeration-automatiskt', 'Förnyas min prenumeration automatiskt?', 'Ja. Din prenumeration förnyas automatiskt. På Mina sidor under fliken Prenumeration ser du detaljer om ditt abonnemang, till exempel förnyelsedatum, fakturor och betalningsmetod.', 'Ja. Din prenumeration förnyas automatiskt. På Mina sidor under fliken Prenumeration ser du detaljer om ditt abonnemang, till exempel förnyelsedatum, fakturor…', 'Prenumeration', 'prenumeration', 'Prenumeration', 1),
  ('kan-jag-uppgradera-min-prenumeration', 'Kan jag uppgradera min prenumeration?', 'Ja. Om du behöver uppgradera ditt abonnemang kan du exempelvis utöka din länkkredit direkt på Mina sidor. Under fliken Prenumeration kan du köpa fler länkar, och uppgraderingen sker direkt på ditt konto.', 'Ja. Om du behöver uppgradera ditt abonnemang kan du exempelvis utöka din länkkredit direkt på Mina sidor.', 'Prenumeration', 'prenumeration', 'Prenumeration', 2),
  ('kan-jag-lagga-till-familjemedlemmar-pa-mitt-konto', 'Kan jag lägga till familjemedlemmar på mitt konto?', 'Nej. Ditt konto är personligt och kopplat till ditt personnummer. Om dina familjemedlemmar också vill ansluta sig till oss är de självklart varmt välkomna att teckna egna konton.', 'Nej. Ditt konto är personligt och kopplat till ditt personnummer.', 'Prenumeration', 'prenumeration', 'Prenumeration', 3),
  ('jag-har-fatt-en-faktura-men-trodde-att-mitt-abonnemang-var-uppsagt', 'Jag har fått en faktura men trodde att mitt abonnemang var uppsagt', 'Om du har sagt upp ditt abonnemang avslutas det alltid vid bindningstidens slut. Det betyder att du får fakturor fram till dess att bindningstiden löper ut. Du kan se exakt slutdatum på Mina sidor → Prenumeration.', 'Om du har sagt upp ditt abonnemang avslutas det alltid vid bindningstidens slut. Det betyder att du får fakturor fram till dess att bindningstiden löper ut.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 0),
  ('jag-hittar-inte-min-faktura-var-ligger-den', 'Jag hittar inte min faktura, var ligger den?', 'Fakturan levereras alltid på det sätt som passar dig bäst och om du inte själv har valt något annat skickas den automatiskt till Kivra. Du kan även få din faktura via mejl (kom ihåg att kontrollera skräpposten), per SMS eller som postutskick. Oavsett hur du får fakturan finns en kopia alltid på Mina sidor under "Fakturor".', 'Fakturan levereras alltid på det sätt som passar dig bäst och om du inte själv har valt något annat skickas den automatiskt till Kivra.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 1),
  ('jag-har-fatt-en-paminnelse-fast-jag-redan-betalat', 'Jag har fått en påminnelse fast jag redan betalat', 'Om du har fått en påminnelse trots att du redan har betalat kan det bero på att betalningen registrerades efter att påminnelsen skickades, eller att betalningen saknade OCR-nummer och därför inte kunde matchas direkt. Har du betalat men ändå fått en påminnelse är du alltid välkommen att kontakta oss. Skicka då gärna med belopp, fakturanummer och betalningsdatum så hjälper vi dig att matcha betalningen.', 'Om du har fått en påminnelse trots att du redan har betalat kan det bero på att betalningen registrerades efter att påminnelsen skickades, eller att…', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 2),
  ('jag-rakade-betala-med-fel-ocr-fel-referens', 'Jag råkade betala med fel OCR / fel referens', 'Ingen fara om du har råkat betala med fel OCR eller på annat sätt. Skicka bara in beloppet, datumet för betalningen och ditt namn så hittar vi transaktionen och matchar den manuellt åt dig.', 'Ingen fara om du har råkat betala med fel OCR eller på annat sätt.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 3),
  ('jag-vill-betala-med-autogiro-istallet-for-manadsfaktura-hur-gor-jag', 'Jag vill betala med autogiro istället för månadsfaktura, hur gör jag?', 'Logga in på Mina sidor, klicka på fliken "Prenumeration" och lägg till autogiro.', 'Logga in på Mina sidor, klicka på fliken "Prenumeration" och lägg till autogiro.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 4),
  ('jag-har-rakat-betala-samma-faktura-tva-ganger-vad-gor-jag', 'Jag har råkat betala samma faktura två gånger, vad gör jag?', 'Ingen fara. Om du råkat betala en faktura dubbelt dras det överbetalda beloppet automatiskt av från din nästa faktura.', 'Ingen fara. Om du råkat betala en faktura dubbelt dras det överbetalda beloppet automatiskt av från din nästa faktura.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 5),
  ('jag-vill-ha-en-kopia-av-fakturan', 'Jag vill ha en kopia av fakturan', 'Du kan ladda ner alla fakturor på Mina sidor → Prenumeration.', 'Du kan ladda ner alla fakturor på Mina sidor → Prenumeration.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 6),
  ('nar-kommer-fakturan', 'När kommer fakturan?', 'Fakturan skapas månadsvis enligt ditt abonnemang. Den skickas normalt samma dag den skapas via ditt valda leveranssätt samt finns på Mina sidor.', 'Fakturan skapas månadsvis enligt ditt abonnemang. Den skickas normalt samma dag den skapas via ditt valda leveranssätt samt finns på Mina sidor.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 7),
  ('min-faktura-ser-fel-ut', 'Min faktura ser fel ut', 'Kontrollera följande innan du kontaktar oss:
Har du ett aktivt abonnemang?
Har du uppdaterat eller ändrat något?
Har du en bindningstid som fortfarande löper?
Om något fortfarande ser fel ut, mejla oss så hjälper vi dig.', 'Kontrollera följande innan du kontaktar oss: Har du ett aktivt abonnemang? Har du uppdaterat eller ändrat något? Har du en bindningstid som fortfarande löper?', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 8),
  ('jag-har-inte-kivra-var-hamnar-min-faktura-da', 'Jag har inte Kivra, var hamnar min faktura då?', 'Ingen fara. Om du inte har Kivra skickas dina fakturor automatiskt till din postadress. Kontakta support om du vill byta leveranssätt.', 'Ingen fara. Om du inte har Kivra skickas dina fakturor automatiskt till din postadress. Kontakta support om du vill byta leveranssätt.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 9),
  ('kan-jag-se-om-min-faktura-ar-betald', 'Kan jag se om min faktura är betald?', 'Ja. Logga in på Mina sidor och gå till fliken "Prenumeration" för att se betalstatus.', 'Ja. Logga in på Mina sidor och gå till fliken "Prenumeration" för att se betalstatus.', 'Fakturasupport', 'fakturasupport', 'Fakturasupport', 10),
  ('vad-hander-med-min-tjanst-om-jag-flyttar', 'Vad händer med min tjänst om jag flyttar?', 'Du behöver inte göra någonting. Vi bevakar folkbokförings­registret och uppdaterar din tjänst automatiskt så snart din nya adress registreras.', 'Du behöver inte göra någonting. Vi bevakar folkbokförings­registret och uppdaterar din tjänst automatiskt så snart din nya adress registreras.', 'Övrigt', 'ovrigt', 'Övrigt', 0),
  ('hur-kontaktar-jag-er', 'Hur kontaktar jag er?', 'Har du frågor, behöver support eller vill diskutera hur vi skyddar dina personuppgifter? Fyll i kontakt­formuläret på vår [kontaktsida](https://www.doldadress.se/kontakt) så hör vi av oss inom 48 timmar på helgfria vardagar.', 'Har du frågor, behöver support eller vill diskutera hur vi skyddar dina personuppgifter?', 'Övrigt', 'ovrigt', 'Övrigt', 1),
  ('har-ni-telefonsupport', 'Har ni telefonsupport?', 'Nej. För att hålla abonnemangskostnaderna för våra kunder erbjuder vi support exklusivt via vårt kontaktformulär. Skicka in din fråga där, så återkommer vi inom 48 timmar på helgfria vardagar med den hjälp du behöver.', 'Nej. För att hålla abonnemangskostnaderna för våra kunder erbjuder vi support exklusivt via vårt kontaktformulär.', 'Övrigt', 'ovrigt', 'Övrigt', 2),
  ('paverkar-en-doldadress-prenumeration-min-vanliga-post', 'Påverkar en Doldadress-prenumeration min vanliga post?', 'Nej. Din vanliga post påverkas inte. DoldAdress skyddar endast dina personuppgifter online och är helt fristående från Postnord, myndigheter och andra postsystem. Leveransen av fysisk post fortsätter därför precis som vanligt.', 'Nej. Din vanliga post påverkas inte. DoldAdress skyddar endast dina personuppgifter online och är helt fristående från Postnord, myndigheter och andra…', 'Övrigt', 'ovrigt', 'Övrigt', 3),
  ('kan-alla-bli-kunder-eller-finns-det-nagra-kriterier', 'Kan alla bli kunder eller finns det några kriterier?', 'Ja, men det finns tre grundkrav:

1. Minst 18 år. Tjänsten är endast tillgänglig för myndiga personer.
2. Folkbokförd i Sverige. Vi kan enbart erbjuda tjänsten till adresser som finns i det svenska folkbokföringsregistret.
3. Inga skyddade personuppgifter. Personer med sekretessmarkerad identitet kan tyvärr inte bli kunder.

Uppfyller du alla kriterier är du varmt välkommen att ansluta dig.', 'Ja, men det finns tre grundkrav: 1. Minst 18 år. Tjänsten är endast tillgänglig för myndiga personer. 2. Folkbokförd i Sverige.', 'Övrigt', 'ovrigt', 'Övrigt', 4),
  ('publicerar-ni-lankar-som-tagits-bort-om-jag-avslutar-mitt-abonnemang', 'Publicerar ni länkar som tagits bort om jag avslutar mitt abonnemang?', 'Nej. Länkar som vi redan har tagit bort publiceras inte igen. Observera dock att nya länkar publiceras över tid. Så länge du är kund identifierar och avindexerar vi dem löpande. Om du avslutar ditt abonnemang upphör den bevakningen, vilket innebär att nya länkar kan bli synliga framöver.', 'Nej. Länkar som vi redan har tagit bort publiceras inte igen. Observera dock att nya länkar publiceras över tid.', 'Övrigt', 'ovrigt', 'Övrigt', 5),
  ('ar-kortbetalning-som-autogiro', 'Är kortbetalning som autogiro?', 'Ja! Vid kortbetalning dras beloppet automatiskt från ditt konto varje period, precis som exempelvis en Spotify-prenumeration. Du behöver inte godkänna något manuellt.', 'Ja! Vid kortbetalning dras beloppet automatiskt från ditt konto varje period, precis som exempelvis en Spotify-prenumeration.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 0),
  ('kan-jag-betala-med-swish-istallet-for-kort', 'Kan jag betala med Swish istället för kort?', 'Nej, i dagsläget är vi inte anslutna till Swish.', 'Nej, i dagsläget är vi inte anslutna till Swish.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 1),
  ('min-betalning-misslyckades-pa-grund-av-otillrackligt-saldo-vad-gor-jag', 'Min betalning misslyckades på grund av otillräckligt saldo, vad gör jag?', 'Ingen fara. Om betalningen misslyckas görs ett nytt försök nästa vardag.', 'Ingen fara. Om betalningen misslyckas görs ett nytt försök nästa vardag.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 2),
  ('min-betalning-misslyckades-och-jag-vet-inte-varfor-vad-kan-det-bero-pa', 'Min betalning misslyckades och jag vet inte varför, vad kan det bero på?', 'En betalning kan misslyckas av flera anledningar, till exempel:

• Otillräckligt saldo vid dragningen → kontrollera ditt konto.
• Kortets giltighetstid har gått ut → uppdatera eller lägg till ett nytt kort på Mina sidor under **Prenumeration**.
• Kortet är spärrat → beställ ett nytt kort från banken och lägg till det på Mina sidor.
• Kortet är spärrat för internetköp → öppna det för säkra internetköp i samband med betalning.
• En säkerhetskontroll (t.ex. Verified by Visa eller Mastercard SecureCode) saknas → kontakta din bank.
• Kortet har en daglig/månatlig gräns som överskridits → höj gränsen eller be banken om andra alternativ.', 'En betalning kan misslyckas av flera anledningar, till exempel: • Otillräckligt saldo vid dragningen → kontrollera ditt konto.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 3),
  ('jag-har-bytt-kort-hur-uppdaterar-jag-mina-kortuppgifter', 'Jag har bytt kort, hur uppdaterar jag mina kortuppgifter?', 'Logga in på Mina sidor, gå till fliken Prenumeration och lägg till ditt nya kort.', 'Logga in på Mina sidor, gå till fliken Prenumeration och lägg till ditt nya kort.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 4),
  ('vi-ar-flera-i-familjen-med-konton-hos-er-kan-vi-anvanda-samma-kort', 'Vi är flera i familjen med konton hos er, kan vi använda samma kort?', 'Ja, det går alldeles utmärkt att använda samma betalkort för flera konton.', 'Ja, det går alldeles utmärkt att använda samma betalkort för flera konton.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 5),
  ('jag-fick-mejl-om-att-mitt-abonnemang-sagts-upp-eftersom-jag-missade-betalningen-', 'Jag fick mejl om att mitt abonnemang sagts upp eftersom jag missade betalningen, vad gör jag?', 'Om du fått ett mejl om att ditt konto sagts upp beror det på utebliven betalning. Men ingen fara, du kan enkelt registrera ett nytt konto med samma mejladress som tidigare.', 'Om du fått ett mejl om att ditt konto sagts upp beror det på utebliven betalning.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 6),
  ('var-hittar-jag-specifikation-over-mina-betalningar', 'Var hittar jag specifikation över mina betalningar?', 'Logga in på Mina sidor och gå till fliken Prenumeration. Där hittar du detaljer om alla dina betalningar, kortuppgifter och betalstatus.', 'Logga in på Mina sidor och gå till fliken Prenumeration. Där hittar du detaljer om alla dina betalningar, kortuppgifter och betalstatus.', 'Kortbetalning / Betala direkt', 'kortbetalning-betala-direkt', 'Kortbetalning / Betala direkt', 7),
  ('kan-jag-byta-e-postadressen-som-ar-kopplad-till-mitt-konto', 'Kan jag byta e-postadressen som är kopplad till mitt konto?', 'Ja. Logga in på Mina sidor och gå till fliken Inställningar. Där kan du enkelt uppdatera din e-postadress.', 'Ja. Logga in på Mina sidor och gå till fliken Inställningar. Där kan du enkelt uppdatera din e-postadress.', 'Kontoinställningar', 'kontoinstallningar', 'Kontoinställningar', 0),
  ('hur-byter-jag-losenord', 'Hur byter jag lösenord?', 'Logga in på Mina sidor och gå till fliken Inställningar. Där kan du smidigt ändra ditt lösenord.', 'Logga in på Mina sidor och gå till fliken Inställningar. Där kan du smidigt ändra ditt lösenord.', 'Kontoinställningar', 'kontoinstallningar', 'Kontoinställningar', 1),
  ('hur-loggar-jag-ut-fran-mitt-konto', 'Hur loggar jag ut från mitt konto?', 'Scrolla längst ner i menyraden, där hittar du knappen Logga ut.', 'Scrolla längst ner i menyraden, där hittar du knappen Logga ut.', 'Kontoinställningar', 'kontoinstallningar', 'Kontoinställningar', 2),
  ('hur-lang-angerratt-har-jag', 'Hur lång ångerrätt har jag?', 'Som kund hos oss har du 14 dagars ångerrätt enligt distansavtalslagen. Ångerrätten gäller i 14 dagar från den dag du registrerade dig.', 'Som kund hos oss har du 14 dagars ångerrätt enligt distansavtalslagen. Ångerrätten gäller i 14 dagar från den dag du registrerade dig.', 'Uppsägning och ångerrätt', 'uppsagning-och-angerratt', 'Uppsägning och ångerrätt', 0),
  ('hur-gor-jag-for-att-angra-mitt-kop', 'Hur gör jag för att ångra mitt köp?', 'För att nyttja ångerrätten kontaktar du vår support och uppger att du vill ångra ditt köp. Skicka med kvitto, ditt fullständiga namn och kundnummer. Om det gått mindre än 14 dagar sedan du registrerade dig avslutar vi ditt avtal direkt och återbetalar dig, alternativt krediterar obetalda fakturor.', 'För att nyttja ångerrätten kontaktar du vår support och uppger att du vill ångra ditt köp. Skicka med kvitto, ditt fullständiga namn och kundnummer.', 'Uppsägning och ångerrätt', 'uppsagning-och-angerratt', 'Uppsägning och ångerrätt', 1),
  ('hur-sager-jag-upp-mitt-abonnemang', 'Hur säger jag upp mitt abonnemang?', 'Du kan när som helst säga upp ditt abonnemang till nästa förnyelseperiod genom att logga in på Mina sidor. Gå till fliken Prenumeration, välj Information och scrolla ner till Ändra din prenumeration för att avsluta.', 'Du kan när som helst säga upp ditt abonnemang till nästa förnyelseperiod genom att logga in på Mina sidor.', 'Uppsägning och ångerrätt', 'uppsagning-och-angerratt', 'Uppsägning och ångerrätt', 2),
  ('kan-jag-saga-upp-nar-som-helst', 'Kan jag säga upp när som helst?', 'Ja, du kan säga upp ditt abonnemang inför nästa förnyelseperiod. Beroende på vilket abonnemang du valt gäller 3, 6 eller 12 månaders bindningstid. Abonnemanget förnyas automatiskt och detaljer hittar du på Mina sidor.', 'Ja, du kan säga upp ditt abonnemang inför nästa förnyelseperiod. Beroende på vilket abonnemang du valt gäller 3, 6 eller 12 månaders bindningstid.', 'Uppsägning och ångerrätt', 'uppsagning-och-angerratt', 'Uppsägning och ångerrätt', 3),
  ('kan-ni-saga-upp-avtalet-at-mig', 'Kan ni säga upp avtalet åt mig?', 'Ja, kontakta vår support om du vill ha hjälp med uppsägningen. Skicka då med ditt fullständiga namn, kundnummer och e-postadress så vi kan identifiera dig. På Mina sidor kan du också se datum för sista betalning och när ditt abonnemang upphör efter vi genomfört din uppsägning.', 'Ja, kontakta vår support om du vill ha hjälp med uppsägningen. Skicka då med ditt fullständiga namn, kundnummer och e-postadress så vi kan identifiera dig.', 'Uppsägning och ångerrätt', 'uppsagning-och-angerratt', 'Uppsägning och ångerrätt', 4),
  ('jag-far-meddelandet-att-min-e-postadress-inte-ar-registrerad-vad-gor-jag', 'Jag får meddelandet att min e-postadress inte är registrerad, vad gör jag?', 'Det beror på att du ännu inte har registrerat ditt konto på Mina sidor. För att kunna logga in behöver du först skapa ditt konto via registreringslänken du fick när du blev kund. Länken är giltig i 7 dagar från registreringsdatumet. Har tiden gått ut kan du kontakta vår support så skickar vi en ny länk. När ditt konto är registrerat loggar du in som vanligt med e-postadress och lösenord.', 'Det beror på att du ännu inte har registrerat ditt konto på Mina sidor.', 'Teknisk support', 'teknisk-support', 'Teknisk support', 0),
  ('jag-kan-inte-logga-in-med-mitt-losenord-hur-gor-jag', 'Jag kan inte logga in med mitt lösenord, hur gör jag?', 'Klicka på Glömt lösenord vid inloggningen. Då får du en engångskod skickad till din e-post, som du använder för att logga in och sedan ändra ditt lösenord direkt på Mina sidor. Om du får felmeddelande även vid återställning, kontakta vår support så hjälper vi dig att återställa kontot. Av säkerhetsskäl behöver vi då först verifiera din identitet.', 'Klicka på Glömt lösenord vid inloggningen. Då får du en engångskod skickad till din e-post, som du använder för att logga in och sedan ändra ditt lösenord…', 'Teknisk support', 'teknisk-support', 'Teknisk support', 1),
  ('jag-kan-inte-logga-in-eftersom-jag-inte-har-betalat-avgiften-vad-gor-jag', 'Jag kan inte logga in eftersom jag inte har betalat avgiften, vad gör jag?', 'Om ditt abonnemang har avslutats på grund av utebliven betalning går det tyvärr inte att återuppta kontot. Du kan däremot registrera ett nytt konto och använda samma e-postadress som tidigare.', 'Om ditt abonnemang har avslutats på grund av utebliven betalning går det tyvärr inte att återuppta kontot.', 'Teknisk support', 'teknisk-support', 'Teknisk support', 2),
  ('nar-jag-forsoker-registrera-mig-star-det-att-mitt-personnummer-ar-ogiltigt-varfo', 'När jag försöker registrera mig står det att mitt personnummer är ogiltigt, varför?', 'Det kan bero på flera orsaker, de vanligaste orsakerna är: att du inte är folkbokförd i Sverige, att du är under 18 år, att du har skyddade uppgifter. Om inget av detta stämmer in på dig, kontakta vår support för teknisk felsökning, så hjälper vi dig.', 'Det kan bero på flera orsaker, de vanligaste orsakerna är: att du inte är folkbokförd i Sverige, att du är under 18 år, att du har skyddade uppgifter.', 'Teknisk support', 'teknisk-support', 'Teknisk support', 3),
  ('nar-jag-forsoker-skicka-in-lankar-for-avindexering-pa-mina-sidor-far-jag-felmedd', 'När jag försöker skicka in länkar för avindexering på Mina sidor får jag felmeddelandet "ange giltig URL", vad betyder det?', 'Det betyder att länken du försöker skicka in inte är korrekt ifylld. Kontrollera att du kopierat hela webbadressen direkt från webbläsarens adressfält. Om du behöver hjälp kan du följa vår steg-för-steg-guide här: Avindexeringsguide.', 'Det betyder att länken du försöker skicka in inte är korrekt ifylld. Kontrollera att du kopierat hela webbadressen direkt från webbläsarens adressfält.', 'Teknisk support', 'teknisk-support', 'Teknisk support', 4),
  ('hur-kontaktar-jag-supporten-pa-basta-satt', 'Hur kontaktar jag supporten på bästa sätt?', 'Du når oss via kontaktformuläret på vår hemsida. När du skickar in ditt ärende får du alltid en bekräftelse via e-post med ett ärendenummer.', 'Du når oss via kontaktformuläret på vår hemsida. När du skickar in ditt ärende får du alltid en bekräftelse via e-post med ett ärendenummer.', 'Vår support', 'var-support', 'Vår support', 0),
  ('hur-snabbt-far-jag-svar-fran-supporten', 'Hur snabbt får jag svar från supporten?', 'Vår support är bemannad under helgfria vardagar. Vi gör alltid vårt bästa för att återkomma så snabbt som möjligt och normalt får du svar inom två arbetsdagar.', 'Vår support är bemannad under helgfria vardagar. Vi gör alltid vårt bästa för att återkomma så snabbt som möjligt och normalt får du svar inom två arbetsdagar.', 'Vår support', 'var-support', 'Vår support', 1),
  ('vad-gor-jag-om-jag-inte-fatt-nagot-svar-fran-supporten', 'Vad gör jag om jag inte fått något svar från supporten?', 'Kontrollera gärna först att vårt bekräftelsemejl med ditt ärendenummer inte har hamnat i skräppost. Skicka in en ny förfrågan om du inte fått något bekräftelsemail. Om du däremot har fått ett ärendenummer betyder det att ditt ärende är registrerat hos oss, och då återkommer vi så snart vi kan.', 'Kontrollera gärna först att vårt bekräftelsemejl med ditt ärendenummer inte har hamnat i skräppost.', 'Vår support', 'var-support', 'Vår support', 2),
  ('har-ni-telefonsupport-2', 'Har ni telefonsupport?', 'Nej, vi erbjuder support via kontaktformulär med e-post.', 'Nej, vi erbjuder support via kontaktformulär med e-post.', 'Vår support', 'var-support', 'Vår support', 3),
  ('kan-ni-skydda-mig-som-brottsoffer-jag-ar-utsatt-for-hot-och-behover-dolja-min-id', 'Kan ni skydda mig som brottsoffer? Jag är utsatt för hot och behöver dölja min identitet.', 'Om du är utsatt för brott eller hot rekommenderar vi starkt att du kontaktar polisen. Polismyndigheten kan erbjuda ett mer omfattande skydd för brottsoffer. Med vår tjänst blir det svårare att hitta dina uppgifter online, men vi kan inte ersätta det skydd polisen kan ge. Du är självklart också välkommen att bli kund hos oss också.', 'Om du är utsatt för brott eller hot rekommenderar vi starkt att du kontaktar polisen. Polismyndigheten kan erbjuda ett mer omfattande skydd för brottsoffer.', 'Övriga frågor', 'ovriga-fragor', 'Övriga frågor', 0),
  ('kan-jag-kopa-licenser-till-mitt-foretag-for-mina-anstallda', 'Kan jag köpa licenser till mitt företag för mina anställda?', 'Ja! Vi erbjuder flexibla företagslösningar anpassade efter ert behov, oavsett antal anställda eller verksamhetens omfattning. En gemensam företagsprenumeration är ofta betydligt mer kostnadseffektiv än flera enskilda abonnemang. Skicka din förfrågan här så hjälper vi dig att hitta rätt lösning: doldadress.se/foretag', 'Ja! Vi erbjuder flexibla företagslösningar anpassade efter ert behov, oavsett antal anställda eller verksamhetens omfattning.', 'Övriga frågor', 'ovriga-fragor', 'Övriga frågor', 1),
  ('jag-vill-reklamera-hur-gor-jag', 'Jag vill reklamera, hur gör jag?', 'Vid reklamationsärenden kontaktar du vår support.', 'Vid reklamationsärenden kontaktar du vår support.', 'Övriga frågor', 'ovriga-fragor', 'Övriga frågor', 2),
  ('tar-ni-bort-information-om-min-bil-pa-biluppgifter-se', 'Tar ni bort information om min bil på Biluppgifter.se?', 'Ja, din profillänk tas bort från Biluppgifter.se när du döljs på upplysningssajterna. Då går det inte längre att klicka vidare till din profil. Själva fordonsuppgifterna hämtas dock från Transportstyrelsen och dessa kan vi inte radera. Om det är en Google-länk till Biluppgifter.se kan vi däremot hjälpa dig att avindexera den.', 'Ja, din profillänk tas bort från Biluppgifter.se när du döljs på upplysningssajterna. Då går det inte längre att klicka vidare till din profil.', 'Övriga frågor', 'ovriga-fragor', 'Övriga frågor', 3),
  ('paverkas-min-postutdelning-nar-jag-ar-kund-hos-er', 'Påverkas min postutdelning när jag är kund hos er?', 'Nej, din postutdelning påverkas inte.', 'Nej, din postutdelning påverkas inte.', 'Övriga frågor', 'ovriga-fragor', 'Övriga frågor', 4),
  ('vad-hander-om-jag-flyttar-nar-jag-ar-kund-hos-er', 'Vad händer om jag flyttar när jag är kund hos er?', 'För dig blir det ingen skillnad. Vi övervakar din folkbokföringsadress och den uppdateras automatiskt på Mina sidor när du flyttar. Om din nya adress gör att du blir synlig på någon upplysningssajt får du en varning direkt från oss. Vi kan även hjälpa dig att avindexera nya Google-länkar som dyker upp kopplade till din nya adress.', 'För dig blir det ingen skillnad. Vi övervakar din folkbokföringsadress och den uppdateras automatiskt på Mina sidor när du flyttar.', 'Övriga frågor', 'ovriga-fragor', 'Övriga frågor', 5),
  ('ar-id-skydd-samma-sak-som-skyddad-identitet', 'Är ID-skydd samma sak som skyddad identitet?', 'Nej, ID-skydd är inte samma sak som skyddad identitet. Vårt ID-skydd hjälper dig istället att upptäcka och förebygga ID-kapningar.', 'Nej, ID-skydd är inte samma sak som skyddad identitet. Vårt ID-skydd hjälper dig istället att upptäcka och förebygga ID-kapningar.', 'ID-skydd', 'id-skydd', 'ID-skydd', 0),
  ('kan-foretag-gora-en-kreditupplysning-pa-mig-om-jag-anvander-ert-id-skydd', 'Kan företag göra en kreditupplysning på mig om jag använder ert ID-skydd?', 'Ja. Företag kan göra kreditupplysningar på dig precis som vanligt. Skillnaden är att du blir direkt notifierad varje gång en kreditupplysning görs i ditt namn.', 'Ja. Företag kan göra kreditupplysningar på dig precis som vanligt. Skillnaden är att du blir direkt notifierad varje gång en kreditupplysning görs i ditt namn.', 'ID-skydd', 'id-skydd', 'ID-skydd', 1),
  ('paverkas-min-creditscore-av-att-jag-har-ett-id-skydd', 'Påverkas min creditscore av att jag har ett ID-skydd?', 'Nej. Att använda vårt ID-skydd påverkar inte din kreditscore. Med ID-skyddet kan du istället följa din kreditvärdighet i realtid. Vi varnar dig vid förändringar och hjälper dig att bestrida felaktiga uppgifter om det skulle behövas.', 'Nej. Att använda vårt ID-skydd påverkar inte din kreditscore. Med ID-skyddet kan du istället följa din kreditvärdighet i realtid.', 'ID-skydd', 'id-skydd', 'ID-skydd', 2),
  ('jag-har-fatt-en-notis-om-mitt-skuldsaldo-ar-det-en-skuld-hos-er', 'Jag har fått en notis om mitt skuldsaldo, är det en skuld hos er?', 'Nej. Skuldsaldo är det totala belopp som är registrerat på dig hos Kronofogden. Det avser inte några fakturor eller skulder hos oss. Vi övervakar endast informationen för att kunna uppmärksamma dig på förändringar.', 'Nej. Skuldsaldo är det totala belopp som är registrerat på dig hos Kronofogden. Det avser inte några fakturor eller skulder hos oss.', 'ID-skydd', 'id-skydd', 'ID-skydd', 3),
  ('min-betalning-misslyckades-vad-ska-jag-gora', 'Min betalning misslyckades, vad ska jag göra?', 'Ingen fara! Om din kortbetalning misslyckades första gången idag, kommer vi automatiskt att göra nya försök nästkommande vardag.', 'Ingen fara! Om din kortbetalning misslyckades första gången idag, kommer vi automatiskt att göra nya försök nästkommande vardag.', 'Betalning', 'betalning', 'Betalning', 0),
  ('jag-har-sagt-upp-mitt-avtal-och-far-fakturor-manadsvis-kan-ni-skicka-en-slutfakt', 'Jag har sagt upp mitt avtal och får fakturor månadsvis, kan ni skicka en slutfaktura direkt?', 'Ja, det kan vi. Om du önskar få en slutfaktura för resterande månader, vänligen kontakta vår support via kontaktformuläret: https://www.doldadress.se/support', 'Ja, det kan vi. Om du önskar få en slutfaktura för resterande månader, vänligen kontakta vår support via kontaktformuläret: https://www.doldadress.se/support', 'Betalning', 'betalning', 'Betalning', 1),
  ('jag-fick-mejl-om-att-mitt-abonnemang-ar-uppsagt-jag-glomde-betala-fornyelsen-vad', 'Jag fick mejl om att mitt abonnemang är uppsagt, jag glömde betala förnyelsen. Vad händer nu?', 'Om din kortbetalning misslyckas stängs ditt konto. Om du har fått mejl om att ditt abonnemang sagts upp, kan du inte längre logga in.

Vill du fortsätta använda våra tjänster? Inga problem, registrera ett nytt konto med din e-postadress. Du kan använda samma adress som tidigare.', 'Om din kortbetalning misslyckas stängs ditt konto. Om du har fått mejl om att ditt abonnemang sagts upp, kan du inte längre logga in.', 'Betalning', 'betalning', 'Betalning', 2),
  ('kan-jag-betala-med-swish', 'Kan jag betala med Swish?', 'Nej, i dagsläget erbjuder vi tyvärr inte Swish som betalningsalternativ.', 'Nej, i dagsläget erbjuder vi tyvärr inte Swish som betalningsalternativ.', 'Betalning', 'betalning', 'Betalning', 3),
  ('jag-har-bytt-kort-kan-jag-uppdatera-mina-kortuppgifter', 'Jag har bytt kort,  kan jag uppdatera mina kortuppgifter?', 'Självklart! Logga in på Mina sidor, gå till fliken ”Prenumeration” och uppdatera dina kortuppgifter där.', 'Självklart! Logga in på Mina sidor, gå till fliken ”Prenumeration” och uppdatera dina kortuppgifter där.', 'Betalning', 'betalning', 'Betalning', 4),
  ('gar-det-att-registrera-ett-kort-som-inte-ar-mitt-till-exempel-ett-familjekort', 'Går det att registrera ett kort som inte är mitt, till exempel ett familjekort?', 'Ja, det går bra. Flera personer kan skapa egna konton och använda samma betalkort.', 'Ja, det går bra. Flera personer kan skapa egna konton och använda samma betalkort.', 'Betalning', 'betalning', 'Betalning', 5)
) AS v(slug, title, content, excerpt, category, "categorySlug", tag, "sortOrder")
ON CONFLICT ("tenantId","slug") DO UPDATE
  SET "title" = EXCLUDED."title", "content" = EXCLUDED."content", "excerpt" = EXCLUDED."excerpt",
      "category" = EXCLUDED."category", "categoryId" = EXCLUDED."categoryId", "tags" = EXCLUDED."tags",
      "isActive" = true, "isPublic" = true, "status" = 'published', "sortOrder" = EXCLUDED."sortOrder",
      "updatedAt" = now();

COMMIT;
